-- Apply the whole schema in order.
\ir 001_foundations.sql
\ir 002_property.sql
\ir 003_leasing_and_debt.sql
\ir 004_tax.sql
\ir 005_risk_ledger_documents.sql
\ir 006_integrity.sql
\ir 007_deadlines_hazards_market.sql
\ir 008_tax_profile_elections_disclosures.sql
\ir 009_deadline_sweep_identity.sql
\ir 010_nationwide_foundations.sql
\ir 011_bank_import.sql
\ir 012_reporting.sql
\ir 013_rent_charges.sql
\ir 014_review_hardening.sql
\ir 015_document_extraction.sql
\ir 016_maintenance.sql
\ir 017_replacement_history.sql
\ir 018_screening.sql
\ir 019_assessment_records.sql
\ir 020_income_tax_rates_leave_the_profile.sql
\ir 021_escalation_value_gets_a_unit.sql
\ir 022_lease_dates_bind_their_charges.sql
\ir 023_a_receipt_pays_out_at_most_once.sql
\ir 024_tax_collection_domain.sql
\ir 025_tax_payment_deadline_kinds.sql
