/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/coverage/jurisdictions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Coverage Jurisdictions */
    get: operations['coverage_jurisdictions_coverage_jurisdictions_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/deadlines': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Deadlines */
    get: operations['list_deadlines_deadlines_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/entities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Entities */
    get: operations['list_entities_entities_get'];
    put?: never;
    /** Create Entity */
    post: operations['create_entity_entities_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Healthz */
    get: operations['healthz_healthz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledger': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ledger Register */
    get: operations['ledger_register_ledger_get'];
    put?: never;
    /** Append Ledger Event */
    post: operations['append_ledger_event_ledger_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledger/{event_uuid}/reverse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reverse Ledger Event */
    post: operations['reverse_ledger_event_ledger__event_uuid__reverse_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/properties': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Properties */
    get: operations['list_properties_properties_get'];
    put?: never;
    /** Create Property */
    post: operations['create_property_properties_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/properties/{property_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Property */
    get: operations['get_property_properties__property_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/properties/{property_id}/dossier': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Dossier */
    get: operations['read_dossier_properties__property_id__dossier_get'];
    put?: never;
    /** Assemble Dossier */
    post: operations['assemble_dossier_properties__property_id__dossier_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readyz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readyz */
    get: operations['readyz_readyz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sweep/deadlines': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sweep Deadlines */
    post: operations['sweep_deadlines_sweep_deadlines_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ChainLink */
    ChainLink: {
      /** Level */
      level: string;
      /** Name */
      name: string;
    };
    /** ComponentOut */
    ComponentOut: {
      /** Code */
      code: string;
      /** Condition */
      condition: string;
      /** Confidence */
      confidence: number;
      /** Derived From */
      derived_from: string | null;
      /** Display Name */
      display_name: string;
      /** Installed Year High */
      installed_year_high: number | null;
      /** Installed Year Low */
      installed_year_low: number | null;
      /** Life Years High */
      life_years_high: number | null;
      /** Life Years Low */
      life_years_low: number | null;
      /** Provenance Kind */
      provenance_kind: string;
      /** System */
      system: string;
    };
    /** CoverageGapOut */
    CoverageGapOut: {
      /** Domain */
      domain: string;
      /** Message */
      message: string;
      /** Property Id */
      property_id: string;
      /**
       * Reason
       * @constant
       */
      reason: 'no_state_jurisdiction';
      /** State */
      state: string;
    };
    /** CoverageReport */
    CoverageReport: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Gaps */
      gaps: components['schemas']['CoverageGapOut'][];
      /** Properties */
      properties: components['schemas']['PropertyCoverage'][];
    };
    /** DeadlineOut */
    DeadlineOut: {
      /** Citation */
      citation: string;
      /**
       * Due On
       * Format: date
       */
      due_on: string;
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Note */
      note: string | null;
      /** Property Label */
      property_label: string | null;
      /** Status */
      status: string;
      /** Window Opens On */
      window_opens_on: string | null;
    };
    /** DefectOut */
    DefectOut: {
      /** Affects Financing */
      affects_financing: boolean;
      /** Affects Insurance */
      affects_insurance: boolean;
      /** Affects Safety */
      affects_safety: boolean;
      /** Citation */
      citation: string | null;
      /** Derived From */
      derived_from: string | null;
      /** Kind */
      kind: string;
      /** Status */
      status: string;
      /** Triggers Disclosure */
      triggers_disclosure: boolean;
    };
    /** DomainCoverage */
    DomainCoverage: {
      /** Calendar Key */
      calendar_key?: string | null;
      /** Calendar Registered */
      calendar_registered?: boolean | null;
      /** Citation */
      citation?: string | null;
      /** Source */
      source?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'covered' | 'no_rules_loaded';
    };
    /** DossierOut */
    DossierOut: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** Steps */
      steps: components['schemas']['DossierStepOut'][];
      /** Sweep */
      sweep: {
        [key: string]: unknown;
      };
    };
    /** DossierStepOut */
    DossierStepOut: {
      /** Detail */
      detail: string;
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'skipped' | 'failed';
    };
    /** DossierView */
    DossierView: {
      /** City */
      city: string;
      /** Components */
      components: components['schemas']['ComponentOut'][];
      /** County */
      county: string | null;
      /** Deadlines */
      deadlines: components['schemas']['DeadlineOut'][];
      /** Defects */
      defects: components['schemas']['DefectOut'][];
      /** Entity Id */
      entity_id: string;
      /** Hazards */
      hazards: components['schemas']['HazardOut'][];
      /** Id */
      id: string;
      /** Jurisdiction Chain */
      jurisdiction_chain: components['schemas']['ChainLink'][];
      /** Kind */
      kind: string;
      /** Label */
      label: string;
      /** Latitude */
      latitude: number | null;
      /** Longitude */
      longitude: number | null;
      /** Postal Code */
      postal_code: string;
      /** State */
      state: string;
      /** Street 1 */
      street_1: string;
      /** Year Built */
      year_built: number | null;
    };
    /** EntityIn */
    EntityIn: {
      /** Formation State */
      formation_state?: string | null;
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'individual'
        | 'joint'
        | 'llc'
        | 'series_llc_cell'
        | 'limited_partnership'
        | 's_corporation'
        | 'c_corporation'
        | 'revocable_trust'
        | 'irrevocable_trust'
        | 'land_trust';
      /** Name */
      name: string;
    };
    /** EntityOut */
    EntityOut: {
      /** Formation State */
      formation_state?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'individual'
        | 'joint'
        | 'llc'
        | 'series_llc_cell'
        | 'limited_partnership'
        | 's_corporation'
        | 'c_corporation'
        | 'revocable_trust'
        | 'irrevocable_trust'
        | 'land_trust';
      /** Name */
      name: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HazardOut */
    HazardOut: {
      /** Base Flood Elevation Ft */
      base_flood_elevation_ft: number | null;
      /** In Special Flood Hazard Area */
      in_special_flood_hazard_area: boolean | null;
      /** Kind */
      kind: string;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /** Zone */
      zone: string | null;
    };
    /** Health */
    Health: {
      /**
       * Status
       * @constant
       */
      status: 'alive';
    };
    /** LedgerEntryIn */
    LedgerEntryIn: {
      /** Amount */
      amount: number | string;
      /** Capitalisation Rationale */
      capitalisation_rationale?: string | null;
      /**
       * Category
       * @enum {string}
       */
      category:
        | 'rent'
        | 'other_income'
        | 'late_fee'
        | 'deposit_received'
        | 'deposit_returned'
        | 'mortgage_interest'
        | 'mortgage_principal'
        | 'property_tax'
        | 'insurance'
        | 'repairs'
        | 'capital_improvement'
        | 'utilities'
        | 'management_fee'
        | 'hoa'
        | 'legal_professional'
        | 'advertising'
        | 'supplies'
        | 'travel'
        | 'acquisition_cost'
        | 'disposition_cost'
        | 'owner_contribution'
        | 'owner_distribution';
      /** Counterparty */
      counterparty?: string | null;
      /** Entity Id */
      entity_id?: string | null;
      /** Is Capital */
      is_capital?: boolean | null;
      /** Lease Id */
      lease_id?: string | null;
      /** Memo */
      memo?: string | null;
      /**
       * Occurred On
       * Format: date
       */
      occurred_on: string;
      /** Property Id */
      property_id?: string | null;
      /** Unit Id */
      unit_id?: string | null;
    };
    /** LedgerEventOut */
    LedgerEventOut: {
      /** Amount */
      amount: string;
      /** Capitalisation Rationale */
      capitalisation_rationale: string | null;
      /** Category */
      category: string;
      /** Counterparty */
      counterparty: string | null;
      /** Entity Id */
      entity_id: string | null;
      /** Event Uuid */
      event_uuid: string;
      /** Is Capital */
      is_capital: boolean | null;
      /** Lease Id */
      lease_id: string | null;
      /** Memo */
      memo: string | null;
      /**
       * Occurred On
       * Format: date
       */
      occurred_on: string;
      /** Property Id */
      property_id: string | null;
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string;
      /** Reversed */
      reversed: boolean;
      /** Reverses Event Uuid */
      reverses_event_uuid: string | null;
      /** Unit Id */
      unit_id: string | null;
    };
    /** LedgerRegister */
    LedgerRegister: {
      /** Events */
      events: components['schemas']['LedgerEventOut'][];
      /** Net */
      net: string;
      /** Total In */
      total_in: string;
      /** Total Out */
      total_out: string;
    };
    /** PropertyCoverage */
    PropertyCoverage: {
      /** Domains */
      domains: {
        [key: string]: components['schemas']['DomainCoverage'];
      };
      /** Label */
      label: string;
      /** Property Id */
      property_id: string;
      resolution: components['schemas']['Resolution'];
      /** State */
      state: string;
    };
    /** PropertyIn */
    PropertyIn: {
      /** City */
      city: string;
      /** County */
      county?: string | null;
      /**
       * Entity Id
       * Format: uuid
       */
      entity_id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'single_family'
        | 'duplex'
        | 'triplex'
        | 'fourplex'
        | 'small_multifamily'
        | 'condominium'
        | 'townhouse'
        | 'manufactured'
        | 'mixed_use'
        | 'land';
      /** Label */
      label: string;
      /** Postal Code */
      postal_code: string;
      /** State */
      state: string;
      /** Street 1 */
      street_1: string;
      /** Year Built */
      year_built?: number | null;
    };
    /** PropertyOut */
    PropertyOut: {
      /** City */
      city: string;
      /** County */
      county?: string | null;
      /**
       * Entity Id
       * Format: uuid
       */
      entity_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Jurisdiction Id */
      jurisdiction_id: string | null;
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | 'single_family'
        | 'duplex'
        | 'triplex'
        | 'fourplex'
        | 'small_multifamily'
        | 'condominium'
        | 'townhouse'
        | 'manufactured'
        | 'mixed_use'
        | 'land';
      /** Label */
      label: string;
      /** Postal Code */
      postal_code: string;
      /** State */
      state: string;
      /** Street 1 */
      street_1: string;
      /** Year Built */
      year_built?: number | null;
    };
    /** PropertySummary */
    PropertySummary: {
      /** City */
      city: string;
      /** Component Count */
      component_count: number;
      /** Defect Count */
      defect_count: number;
      /** Id */
      id: string;
      /** Jurisdiction */
      jurisdiction: string | null;
      /** Kind */
      kind: string;
      /** Label */
      label: string;
      /** Next Deadline On */
      next_deadline_on: string | null;
      /** Postal Code */
      postal_code: string;
      /** State */
      state: string;
      /** Street 1 */
      street_1: string;
      /** Year Built */
      year_built: number | null;
    };
    /** Readiness */
    Readiness: {
      /** Migrations */
      migrations: number;
      /**
       * Status
       * @constant
       */
      status: 'ready';
    };
    /** Resolution */
    Resolution: {
      /** Chain */
      chain: string[];
      /** Level */
      level: string;
    };
    /** ReversalIn */
    ReversalIn: {
      corrected?: components['schemas']['LedgerEntryIn'] | null;
      /** Memo */
      memo?: string | null;
    };
    /** ReversalOut */
    ReversalOut: {
      corrected: components['schemas']['LedgerEventOut'] | null;
      reversal: components['schemas']['LedgerEventOut'];
    };
    /** SweepGapOut */
    SweepGapOut: {
      /** Detail */
      detail: string;
      /** Domain */
      domain: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /**
       * Reason
       * @enum {string}
       */
      reason: 'no_state_jurisdiction' | 'no_rule_for_domain' | 'calendar_key_unregistered';
      /** State */
      state: string;
    };
    /** SweepOut */
    SweepOut: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Coverage Gaps */
      coverage_gaps: components['schemas']['SweepGapOut'][];
      /** Inserted */
      inserted: {
        [key: string]: number;
      };
      /** Total */
      total: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  coverage_jurisdictions_coverage_jurisdictions_get: {
    parameters: {
      query?: {
        as_of?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CoverageReport'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_deadlines_deadlines_get: {
    parameters: {
      query?: {
        due_before?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeadlineOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_entities_entities_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntityOut'][];
        };
      };
    };
  };
  create_entity_entities_post: {
    parameters: {
      query?: never;
      header?: {
        'x-actor'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntityIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntityOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  ledger_register_ledger_get: {
    parameters: {
      query?: {
        property_id?: string | null;
        category?:
          | (
              | 'rent'
              | 'other_income'
              | 'late_fee'
              | 'deposit_received'
              | 'deposit_returned'
              | 'mortgage_interest'
              | 'mortgage_principal'
              | 'property_tax'
              | 'insurance'
              | 'repairs'
              | 'capital_improvement'
              | 'utilities'
              | 'management_fee'
              | 'hoa'
              | 'legal_professional'
              | 'advertising'
              | 'supplies'
              | 'travel'
              | 'acquisition_cost'
              | 'disposition_cost'
              | 'owner_contribution'
              | 'owner_distribution'
            )
          | null;
        occurred_from?: string | null;
        occurred_to?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LedgerRegister'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  append_ledger_event_ledger_post: {
    parameters: {
      query?: never;
      header?: {
        'x-actor'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LedgerEntryIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LedgerEventOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reverse_ledger_event_ledger__event_uuid__reverse_post: {
    parameters: {
      query?: never;
      header?: {
        'x-actor'?: string;
      };
      path: {
        event_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReversalIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReversalOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_properties_properties_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PropertySummary'][];
        };
      };
    };
  };
  create_property_properties_post: {
    parameters: {
      query?: never;
      header?: {
        'x-actor'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PropertyIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PropertyOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_property_properties__property_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        property_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PropertyOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_dossier_properties__property_id__dossier_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        property_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DossierView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  assemble_dossier_properties__property_id__dossier_post: {
    parameters: {
      query?: {
        as_of?: string | null;
      };
      header?: {
        'x-actor'?: string;
      };
      path: {
        property_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DossierOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Readiness'];
        };
      };
    };
  };
  sweep_deadlines_sweep_deadlines_post: {
    parameters: {
      query?: {
        as_of?: string | null;
      };
      header?: {
        'x-actor'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SweepOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
